### PR TITLE
Fix/replace new urls

### PR DESCRIPTION
**Pull request by vincent-agi**
Fix issue #55 opened by @vincent-inviseo about new urls to call sge services
I replaced `sge-b2b` by `sge-ws`

### CODE REVIEW

**Review by philpep — CHANGES_REQUESTED** [review]
Hi, thanks for this.

I think you will have to add something like:

```python
method.location = method.location.replace(b"/sge-b2b.enedis.fr", b"/sge-ws.enedis.fr")
```

Just after line 216 ```method.location.replace(b".erdf.fr", b".enedis.fr")```.

Also run tests and adapt `test/test_lowatt_enedis.py`, running tests with github was disabled due to long term inactivity, I re-enabled them so they should run when you push on a PR now.

**Comment by vincent-agi** [comment]
Hi @philpep thank you so much for your help.
I will do That later in  the week.

**Comment by philpep** [comment]
A bit more context: urls are defined in wsdl files in `lowatt_enedis/wsdl` which comes from enedis documentation.

At time of writing, wsdl files from documentation still contains old url sge-b2b, I guess they will update it before 04/10/2024

**Comment by philpep** [comment]
Superseeded by #62

**Pull request closed without merging**
